language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "10"
before_install:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest'
  - npm install -g greenkeeper-lockfile
install: npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success:
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
script:
  - npm run qa
  - npm run check-deps
