language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "10"
before_install:
  - if [[ `npm -v` != 6* ]]; then npm install -g npm@6; fi
  - npm install -g greenkeeper-lockfile
install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
before_script: greenkeeper-lockfile-update
script:
  - npm run lint
  - npm run check-deps
after_script: greenkeeper-lockfile-upload
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
after_success:
  - npx semantic-release
