language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
script:
  - npm run qa
  - npm run check-deps

jobs:
  include:
    - stage: release
      script:
        - npm run semantic-release
