language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "10"
  - "9"
  - "8"
install:
  - npm ci
after_success:
  - npx travis-deploy-once && npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
script: npm run lint
