language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "10"
install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
after_success:
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
script:
  - npm run lint
  - npm run check-deps
